/**
 * @anby/platform-sdk/vite — Vite plugin for auto-codegen of Anby app types.
 *
 * PLAN-app-bootstrap-phase2 PR5.
 *
 * Drop into a consumer app's vite.config.ts:
 *
 * ```ts
 * import { anbyVitePlugin } from '@anby/platform-sdk/vite';
 *
 * export default defineConfig({
 *   plugins: [
 *     anbyVitePlugin(),
 *     remix({...}),
 *   ],
 * });
 * ```
 *
 * On every dev start (and on every change to `anby-app.manifest.json`),
 * the plugin reads the manifest's `provides.events` and `requires.events`
 * arrays and writes typed module augmentations to `.anby/types.d.ts`. The
 * SDK's `publishEvent` overload picks up the merged `AppProvidedEvents`
 * interface and gives the dev compile-time errors on unknown event names.
 *
 * The plugin imports `vite` only as a TYPE — `import type { Plugin }` is
 * erased at compile time, so the SDK package does NOT need to ship vite
 * as a runtime dependency. Apps that use this plugin already have vite.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve, isAbsolute } from 'node:path';
import type { Plugin } from 'vite';
import { getInlinedManifest } from '../apps/publish.js';

export interface AnbyVitePluginOptions {
  /** Path to the manifest file relative to vite root. Default: `./anby-app.manifest.json`. */
  manifestPath?: string;
  /** Output path for generated types relative to vite root. Default: `./.anby/types.d.ts`. */
  outFile?: string;
  /**
   * Output path for the wire-format manifest static asset, relative to
   * vite root. Default: `./public/_anby/manifest.json`.
   *
   * The Marketplace Submit-app form fetches this file from
   * `${publicUrl}/_anby/manifest.json` to publish a running app without
   * the operator pasting any JSON. Vite (dev) and Remix (prod) both
   * serve files in `public/` as static assets, so the same artifact
   * works in every runtime — no middleware, no Remix route file.
   */
  manifestArtifactPath?: string;
}

interface ManifestEventsShape {
  provides?: { events?: string[] };
  requires?: { events?: string[] };
}

function renderTypes(provides: string[], requires: string[]): string {
  const sections: string[] = [];

  sections.push('// Generated by @anby/platform-sdk/vite — DO NOT EDIT.');
  sections.push('// Re-runs whenever anby-app.manifest.json changes.');
  sections.push('');
  sections.push("declare module '@anby/platform-sdk' {");

  if (provides.length > 0) {
    sections.push('  interface AppProvidedEvents {');
    for (const name of provides) {
      sections.push(`    ${JSON.stringify(name)}: Record<string, unknown>;`);
    }
    sections.push('  }');
  } else {
    sections.push('  interface AppProvidedEvents {}');
  }

  if (requires.length > 0) {
    sections.push('  interface AppRequiredEvents {');
    for (const name of requires) {
      sections.push(`    ${JSON.stringify(name)}: Record<string, unknown>;`);
    }
    sections.push('  }');
  } else {
    sections.push('  interface AppRequiredEvents {}');
  }

  sections.push('}');
  sections.push('');
  // Pure declaration file marker
  sections.push('export {};');
  sections.push('');

  return sections.join('\n');
}

function readManifestEvents(manifestAbsPath: string): {
  provides: string[];
  requires: string[];
} {
  const raw = readFileSync(manifestAbsPath, 'utf-8');
  const parsed = JSON.parse(raw) as ManifestEventsShape;
  const provides = Array.isArray(parsed.provides?.events) ? parsed.provides!.events! : [];
  const requires = Array.isArray(parsed.requires?.events) ? parsed.requires!.events! : [];
  return { provides, requires };
}

export function anbyVitePlugin(opts: AnbyVitePluginOptions = {}): Plugin {
  const manifestRelative = opts.manifestPath ?? './anby-app.manifest.json';
  const outRelative = opts.outFile ?? './.anby/types.d.ts';
  const artifactRelative =
    opts.manifestArtifactPath ?? './public/_anby/manifest.json';

  let resolvedManifest = '';
  let resolvedOut = '';
  let resolvedArtifact = '';

  function generateTypes() {
    if (!existsSync(resolvedManifest)) {
      console.warn(
        `[anby-vite] manifest not found at ${resolvedManifest} — skipping codegen`,
      );
      return;
    }
    try {
      const { provides, requires } = readManifestEvents(resolvedManifest);
      const content = renderTypes(provides, requires);
      mkdirSync(dirname(resolvedOut), { recursive: true });
      writeFileSync(resolvedOut, content);
    } catch (err) {
      console.warn(
        `[anby-vite] codegen failed: ${(err as Error).message}`,
      );
    }
  }

  /**
   * Generate `public/_anby/manifest.json` — the wire-format manifest
   * with all `provides.entities[].schema` paths resolved to inline JSON
   * content. Vite/Remix serve `public/` as static assets in both dev
   * and production, so this single artifact powers the Marketplace
   * Submit-app form everywhere.
   */
  async function generateManifestArtifact() {
    if (!existsSync(resolvedManifest)) return;
    try {
      const inlined = await getInlinedManifest({
        manifestPath: resolvedManifest,
      });
      mkdirSync(dirname(resolvedArtifact), { recursive: true });
      writeFileSync(resolvedArtifact, JSON.stringify(inlined, null, 2));
    } catch (err) {
      console.warn(
        `[anby-vite] manifest artifact write failed: ${(err as Error).message}`,
      );
    }
  }

  function regenerateAll() {
    generateTypes();
    void generateManifestArtifact();
  }

  return {
    name: '@anby/platform-sdk/vite',

    configResolved(config) {
      // Resolve relative paths against the Vite project root, not cwd.
      // This is robust against pnpm workspaces / symlinks / monorepos.
      const root = config.root;
      resolvedManifest = isAbsolute(manifestRelative)
        ? manifestRelative
        : resolve(root, manifestRelative);
      resolvedOut = isAbsolute(outRelative)
        ? outRelative
        : resolve(root, outRelative);
      resolvedArtifact = isAbsolute(artifactRelative)
        ? artifactRelative
        : resolve(root, artifactRelative);
    },

    buildStart() {
      regenerateAll();
    },

    configureServer(server) {
      // Watch the resolved absolute path. Compare in the change handler
      // against the resolved path so we don't false-trigger on other
      // manifest.json files in the workspace (e.g., node_modules).
      server.watcher.add(resolvedManifest);
      server.watcher.on('change', (changedPath) => {
        if (resolve(changedPath) === resolvedManifest) {
          regenerateAll();
        }
      });
    },
  };
}
