import type { AnbyEvent } from '@anby/contracts';
import crypto from 'crypto';

/**
 * PLAN-app-bootstrap-phase2 PR5: type-safe event registry.
 *
 * Codegen extends these interfaces via TypeScript declaration merging
 * in `.anby/types.d.ts` (auto-generated by `@anby/platform-sdk/vite`
 * from each app's `anby-app.manifest.json`). When empty (no codegen
 * has run), `publishEvent` falls through to the loose `AnbyEvent`
 * overload, so existing untyped callers keep working.
 *
 * Generated file looks like:
 * ```ts
 * declare module '@anby/platform-sdk' {
 *   interface AppProvidedEvents {
 *     'org.node.created': Record<string, unknown>;
 *     'org.node.updated': Record<string, unknown>;
 *   }
 * }
 * ```
 */
export interface AppProvidedEvents {}
export interface AppRequiredEvents {}

export interface EventTransport {
  publish(event: AnbyEvent): Promise<void>;
}

class InMemoryTransport implements EventTransport {
  private events: AnbyEvent[] = [];

  async publish(event: AnbyEvent): Promise<void> {
    this.events.push(event);
  }

  getEvents(): AnbyEvent[] {
    return [...this.events];
  }

  clear(): void {
    this.events = [];
  }
}

let _transport: EventTransport = new InMemoryTransport();

export function configureEventTransport(transport: EventTransport): void {
  _transport = transport;
}

export function createEvent<T>(params: {
  type: string;
  source: string;
  tenantId: string;
  actor: { userId: string; email: string };
  data: T;
  correlationId?: string;
}): AnbyEvent<T> {
  return {
    id: crypto.randomUUID(),
    type: params.type,
    source: params.source,
    tenantId: params.tenantId,
    timestamp: new Date().toISOString(),
    version: '1',
    correlationId: params.correlationId || crypto.randomUUID(),
    actor: params.actor,
    data: params.data,
  };
}

/**
 * Publish an event through the configured transport.
 *
 * Two overloads:
 *  1. Strongly-typed shorthand — pass `{ type, tenantId, actor, data }`
 *     where `type` is constrained to declared `AppProvidedEvents` keys
 *     and `data` is narrowed to that key's payload type. Codegen sets up
 *     this constraint by extending AppProvidedEvents in `.anby/types.d.ts`.
 *     This overload only matches when codegen has run AND the type is a
 *     known event name. Catches typos at compile time.
 *
 *  2. Loose escape hatch — pass a full AnbyEvent built via createEvent().
 *     Always works, even without codegen. Use for events not declared in
 *     the manifest, or for cross-app forwarding.
 */
export async function publishEvent<
  K extends keyof AppProvidedEvents
>(event: {
  type: K;
  tenantId: string;
  source?: string;
  actor: { userId: string; email: string };
  data: AppProvidedEvents[K];
  correlationId?: string;
}): Promise<void>;
export async function publishEvent(event: AnbyEvent): Promise<void>;
export async function publishEvent(
  event: AnbyEvent | {
    type: string;
    tenantId: string;
    source?: string;
    actor: { userId: string; email: string };
    data: unknown;
    correlationId?: string;
  },
): Promise<void> {
  // If the caller passed a partial shape (no id/timestamp/version), build
  // a full envelope on their behalf. Otherwise pass through unchanged.
  const isFullEnvelope =
    'id' in event && 'timestamp' in event && 'version' in event;
  const envelope: AnbyEvent = isFullEnvelope
    ? (event as AnbyEvent)
    : createEvent({
        type: (event as any).type,
        source: (event as any).source ?? '',
        tenantId: (event as any).tenantId,
        actor: (event as any).actor,
        data: (event as any).data,
        correlationId: (event as any).correlationId,
      });
  await _transport.publish(envelope);
}

/**
 * PostgresEventTransport writes events to the app_events DB table.
 * The Event Router service polls this table and routes events to consumers.
 * This is the Phase 1 transport. Phase 2 replaces with KafkaEventTransport.
 * App code doesn't change — only the transport configuration.
 */
export class PostgresEventTransport implements EventTransport {
  private pool: any;

  constructor(private connectionString: string) {}

  private async getPool() {
    if (!this.pool) {
      // Dynamic import to avoid requiring pg as a hard dependency.
      // @ts-ignore — `pg` is an optional peer dep; consumers that use
      // the Postgres transport must install it themselves.
      const { Pool } = await import('pg');
      this.pool = new Pool({ connectionString: this.connectionString });
    }
    return this.pool;
  }

  async publish(event: AnbyEvent): Promise<void> {
    const pool = await this.getPool();
    await pool.query(
      `INSERT INTO app_events (id, tenant_id, event_type, source_app_id, payload, processed, created_at)
       VALUES ($1, $2, $3, $4, $5, false, NOW())`,
      [event.id, event.tenantId, event.type, event.source, JSON.stringify(event)],
    );
  }

  async close(): Promise<void> {
    if (this.pool) {
      await this.pool.end();
      this.pool = null;
    }
  }
}

export { InMemoryTransport };
