import { readFileSync, writeFileSync, mkdirSync, watch, existsSync } from 'node:fs';
import { dirname, resolve, isAbsolute } from 'node:path';
import kleur from 'kleur';

/**
 * `anby app codegen [--watch]` — PLAN-app-bootstrap-phase2 PR5.
 *
 * Reads `anby-app.manifest.json` and writes `.anby/types.d.ts` with
 * TypeScript declaration merging that extends `@anby/platform-sdk`'s
 * `AppProvidedEvents` and `AppRequiredEvents` interfaces. After this
 * runs, calls to `publishEvent({ type: 'org.node.created', ... })` get
 * compile-time autocomplete and typo-detection on the event name.
 *
 * For Vite users, prefer the `@anby/platform-sdk/vite` plugin which runs
 * the same logic automatically as part of the dev server. This CLI
 * exists for non-Vite runtimes (NestJS, plain Node, ESBuild, etc).
 *
 * `--watch` re-runs whenever the manifest file changes. Useful as a
 * background process during dev: `anby app codegen --watch &`.
 */

interface CodegenOptions {
  manifest: string;
  out: string;
  watch?: boolean;
}

interface ManifestEventsShape {
  provides?: { events?: string[] };
  requires?: { events?: string[] };
}

function renderTypes(provides: string[], requires: string[]): string {
  const sections: string[] = [];
  sections.push('// Generated by @anby/cli — DO NOT EDIT.');
  sections.push('// Re-runs whenever anby-app.manifest.json changes.');
  sections.push('');
  sections.push("declare module '@anby/platform-sdk' {");
  if (provides.length > 0) {
    sections.push('  interface AppProvidedEvents {');
    for (const name of provides) {
      sections.push(`    ${JSON.stringify(name)}: Record<string, unknown>;`);
    }
    sections.push('  }');
  } else {
    sections.push('  interface AppProvidedEvents {}');
  }
  if (requires.length > 0) {
    sections.push('  interface AppRequiredEvents {');
    for (const name of requires) {
      sections.push(`    ${JSON.stringify(name)}: Record<string, unknown>;`);
    }
    sections.push('  }');
  } else {
    sections.push('  interface AppRequiredEvents {}');
  }
  sections.push('}');
  sections.push('');
  sections.push('export {};');
  sections.push('');
  return sections.join('\n');
}

function generate(manifestAbs: string, outAbs: string): void {
  if (!existsSync(manifestAbs)) {
    console.error(kleur.red(`✖ Manifest not found at ${manifestAbs}`));
    process.exit(1);
  }
  const raw = readFileSync(manifestAbs, 'utf-8');
  const parsed = JSON.parse(raw) as ManifestEventsShape;
  const provides = Array.isArray(parsed.provides?.events) ? parsed.provides!.events! : [];
  const requires = Array.isArray(parsed.requires?.events) ? parsed.requires!.events! : [];
  const content = renderTypes(provides, requires);
  mkdirSync(dirname(outAbs), { recursive: true });
  writeFileSync(outAbs, content);
  console.log(
    kleur.green(
      `✔ Wrote ${outAbs} (${provides.length} provided, ${requires.length} required)`,
    ),
  );
}

export async function codegenCommand(options: CodegenOptions): Promise<void> {
  const manifestAbs = isAbsolute(options.manifest)
    ? options.manifest
    : resolve(process.cwd(), options.manifest);
  const outAbs = isAbsolute(options.out)
    ? options.out
    : resolve(process.cwd(), options.out);

  generate(manifestAbs, outAbs);

  if (options.watch) {
    console.log(kleur.dim(`Watching ${manifestAbs} for changes... (Ctrl+C to exit)`));
    let debounce: NodeJS.Timeout | null = null;
    watch(manifestAbs, () => {
      if (debounce) clearTimeout(debounce);
      debounce = setTimeout(() => {
        try {
          generate(manifestAbs, outAbs);
        } catch (err) {
          console.error(kleur.red(`✖ Codegen failed: ${(err as Error).message}`));
        }
      }, 100);
    });
    // Keep process alive
    await new Promise(() => {});
  }
}
