import { z } from 'zod';

/**
 * Source services that may debit/credit AC. Used in audit trail + observability.
 */
export const SourceServiceSchema = z.enum([
  'meeting',
  'okr',
  'god-brain',
  'admin',
  'platform',
]);
export type SourceService = z.infer<typeof SourceServiceSchema>;

/**
 * Bucket from which AC was primarily debited (for reporting / refund logic).
 */
export type BucketPrimary = 'subscription' | 'topup' | 'mixed';

/**
 * A debit request. Amount must be a positive integer (AC units are whole).
 *
 * The SDK derives `idempotencyKey` when you only provide `jobId`. Alternatively
 * you may pass `idempotencyKey` directly if you are controlling it elsewhere
 * (e.g. upstream queue message id).
 */
export const DebitRequestSchema = z
  .object({
    workspaceId: z.string().uuid(),
    amount: z
      .number()
      .int('AC amounts must be whole integers — fractional AC is not supported')
      .positive('AC amount must be greater than zero'),
    /**
     * Business-meaningful job identifier. Two debits with the same
     * `(jobId, kind='debit')` inside the same service are deduplicated by the
     * server — the second call returns the original ledger entry.
     * Either `jobId` or `idempotencyKey` is REQUIRED.
     */
    jobId: z.string().min(1).max(255).optional(),
    /**
     * API-level idempotency key. Generated by the SDK as
     * `sha256(jobId + sourceService)` if omitted. 24h TTL on server.
     */
    idempotencyKey: z.string().min(1).max(255).optional(),
    sourceService: SourceServiceSchema,
    actorUserId: z.string().uuid().optional(),
    metadata: z.record(z.unknown()).optional(),
  })
  .refine((v) => v.jobId || v.idempotencyKey, {
    message: 'Either jobId or idempotencyKey is required',
    path: ['jobId'],
  });
export type DebitRequest = z.infer<typeof DebitRequestSchema>;

export interface DebitResult {
  ledgerEntryId: string;
  amountDebited: number;
  amountFromSubscription: number;
  amountFromTopup: number;
  bucketPrimary: BucketPrimary;
  balanceSubscriptionAfter: number;
  balanceTopupAfter: number;
  totalBalanceAfter: number;
}

/**
 * Refund / credit-back request. Matches a prior debit by `refundForJobId`.
 */
export const RefundRequestSchema = z.object({
  workspaceId: z.string().uuid(),
  refundForJobId: z.string().min(1).max(255),
  reason: z.string().min(1).max(500),
  sourceService: SourceServiceSchema,
  actorUserId: z.string().uuid().optional(),
  metadata: z.record(z.unknown()).optional(),
});
export type RefundRequest = z.infer<typeof RefundRequestSchema>;

export interface RefundResult {
  ledgerEntryId: string;
  amountRefunded: number;
  balanceSubscriptionAfter: number;
  balanceTopupAfter: number;
  totalBalanceAfter: number;
}

export interface BalanceResult {
  workspaceId: string;
  balanceSubscription: number;
  balanceTopup: number;
  total: number;
  cycle: {
    id: string;
    planSnapshot: string;
    periodStart: string;
    periodEnd: string;
    grantedAmount: number;
  } | null;
}

export interface BillingConfig {
  /** Base URL of anby-billing-service, e.g. https://billing.anby.ai */
  baseUrl: string;
  /** Shared HMAC secret (32+ chars, matches billing-service SVC_HMAC_SECRET env) */
  hmacSecret: string;
  /** Identifier of the calling service, used as the HMAC user value */
  serviceName: SourceService;
  /** Optional custom fetch for testing / non-node runtimes */
  fetch?: typeof fetch;
  /** Request timeout in ms (default 10000) */
  timeoutMs?: number;
}
